name       : teamspeak3
version    : 3.1.9
release    : 12
source     :
    - http://dl.4players.de/ts/releases/3.1.9/TeamSpeak3-Client-linux_amd64-3.1.9.run : 54b7e1e3797174964238f4c03c2b6c603155deaf45906c69a6677431a08f9cf5
license    : Distributable # See files/Redistribution.eml
extract    : no
strip      : no
component  : network.im
summary    : Crystal Clear Cross-Platform Voice Communication
description: |
    VoIP software designed with security in mind, featuring crystal clear voice quality, endless customization options, and scalabilty up to thousands of simultaneous users.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - binutils
rundeps    :
    - gconf
setup      : |
    cp $sources/* $workdir/
    sed -i -e 's|^MS_PrintLicense$||g' TeamSpeak3-Client-linux_amd64-$version.run
build      : |
    bash TeamSpeak3-Client-linux_amd64-$version.run --noexec --target $installdir/usr/share/teamspeak3
    cd $installdir/usr/share/teamspeak3
    %patch < $pkgfiles/0001-Fix-error-when-starting-with-symlink.patch
install    : |
    install -dm0755 $installdir/usr/bin
    install -Dm00644 $pkgfiles/teamspeak3.desktop $installdir/usr/share/applications/teamspeak3.desktop
    ln -s /usr/share/teamspeak3/ts3client_runscript.sh $installdir/usr/bin/ts3client_linux_amd64
