name       : teamspeak3
version    : 3.1.4
release    : 7
source     :
    - http://dl.4players.de/ts/releases/3.1.4/TeamSpeak3-Client-linux_amd64-3.1.4.run : 337aec99070366aa3bb82b1bedd8215372b9c74014b198d45d5d6375d1f1c3a8
license    : Distributable # See files/Redistribution.eml
extract    : no
strip      : no
component  : network.im
summary    : Crystal Clear Cross-Platform Voice Communication
description: |
    VoIP software designed with security in mind, featuring crystal clear voice quality, endless customization options, and scalabilty up to thousands of simultaneous users.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrender)
    - binutils
rundeps    :
    - gconf
setup      : |
    cp $sources/* $workdir/
    sed -i -e 's|^MS_PrintLicense$||g' TeamSpeak3-Client-linux_amd64-$version.run
build      : |
    bash TeamSpeak3-Client-linux_amd64-$version.run --target $installdir/usr/share/teamspeak3
install    : |
    install -dm0755 $installdir/usr/bin
    install -Dm00644 $pkgfiles/teamspeak3.desktop $installdir/usr/share/applications/teamspeak3.desktop
    ln -s /usr/share/teamspeak3/ts3client_runscript.sh $installdir/usr/bin/ts3client_linux_amd64
