name       : teamspeak3
version    : 3.5.6
release    : 25
source     :
    - https://files.teamspeak-services.com/releases/client/3.5.6/TeamSpeak3-Client-linux_amd64-3.5.6.run : efbefd4a6c845974563d874f8d46eb8f7ea2919d1f444f9b780357d256884a42
license    : Distributable # See files/Redistribution.eml
extract    : no
strip      : no
component  : network.im
summary    : Crystal Clear Cross-Platform Voice Communication
description: |
    VoIP software designed with security in mind, featuring crystal clear voice quality, endless customization options, and scalabilty up to thousands of simultaneous users.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xscrnsaver)
    - binutils
rundeps    :
    - gconf
setup      : |
    cp $sources/* $workdir/
    sed -i -e 's|^MS_PrintLicense$||g' TeamSpeak3-Client-linux_amd64-$version.run
build      : |
    bash TeamSpeak3-Client-linux_amd64-$version.run --noexec --target $installdir/usr/share/teamspeak3
    cd $installdir/usr/share/teamspeak3
install    : |
    install -dm0755 $installdir/usr/bin
    install -Dm00644 $pkgfiles/teamspeak3.desktop $installdir/usr/share/applications/teamspeak3.desktop
    ln -s /usr/share/teamspeak3/ts3client_runscript.sh $installdir/usr/bin/ts3client_linux_amd64
